<?xml version="1.0"?>
<package format="2">
  <name>myrobot_description</name>
  <version>0.1.0</version>
  <description>Robot description resources: URDF, meshes, Gazebo world and visual materials.</description>
  <maintainer email="w@todo.todo">w</maintainer>
  <license>TODO</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>
  <export/>
</package>
